### PR TITLE
Feature/products endpoint

### PR DESCRIPTION
**Pull request by Insanityandme**
Ok! I would love to see some of you guys testing this locally on your machines. 

I am not done with the error handling but I wanted to still give it a PR go because I need help with handling errors =).

There are quite a few moving parts but I think if you just read and see what's happening in the test you will understand what's happening and if not just ask me and I'll talk about it!

More endpoints needed:
* createProduct - DONE
* getAllProducts - DONE
* Filtering through queries - DONE
* deleting a product - DONE
* getOneProduct - DONE

The one endpoint I have been working on is the biggest one so hopefully the other ones will go smoothly!

### CODE REVIEW

**Comment by Insanityandme** [comment]
I know this isn't working here on github but it works locally, I have a hard time understanding why and I need to see the detailed reports of the github actions automation, is it possible to get more details on this plsss

**Comment by Luxcorel** [comment]
The test uploadProduct() fails on my machine. ProductImageService line 52 seems to be the reason:
```java 
Files.copy(file.getInputStream(), filePath, StandardCopyOption.REPLACE_EXISTING);
```  
It results in:
`java.lang.Exception: Could not save File: test.jpg, src/main/resources/images/cec56a4d-81e1-47eb-8538-bd5f1362c357_test.jpg`

I'll look further into this issue tomorrow, as well as if the CI action can be configured to provide more debug information without creating any issues.

**Comment by Insanityandme** [comment]
> The test uploadProduct() fails on my machine. ProductImageService line 52 seems to be the reason:
> 
> ```java
> Files.copy(file.getInputStream(), filePath, StandardCopyOption.REPLACE_EXISTING);
> ```
> 
> It results in: `java.lang.Exception: Could not save File: test.jpg, src/main/resources/images/cec56a4d-81e1-47eb-8538-bd5f1362c357_test.jpg`
> 
> I'll look further into this issue tomorrow, as well as if the CI action can be configured to provide more debug information without creating any issues.

Thank you! I think I know the issue now!

**Review by Luxcorel — APPROVED** [review]
LGTM

**Pull request merged**
